### ISSUE TITLE
Cannot navigate to Inbox (chat page) from Dashboard

### ISSUE THREAD

**Issue by lingtran** [Gabriel0402/COILFrontEnd#15]
when I click the bubble of a specific learner on the dashboard, it should take me to the chat page and start chatting with that specific person. 

Actual behavior: when I click it, it won't take me to the chat page.

**Comment by lingtran** [comment]
@nicolewang12 Can you try to edit the description of this bug? See issue #16 description as example. :) let me know any questions!

**Comment by Gabriel0402** [comment]
Resolved
