### ISSUE TITLE
Cannot rate dogs who are not mine in Dashboard page

### ISSUE THREAD

**Issue by lingtran** [Gabriel0402/COILFrontEnd#17]
**Expected behavior**
As a user, when I visit the Dashboard page, I can rate dogs who are not mine, so that the number of stars I give represents how helpful the dog's caretaker has been in answering my questions. I cannot rate my own dog because that'll be super biased.

**Actual behavior**
When I visit the Dashboard page, I can only rate my own dog.

**Comment by nicolewang12** [comment]
in this page, I cannot rate any other dog or my own dog is what it should be :)

**Comment by lingtran** [comment]
This is also same issue on homepage that needs to be fixed. TODO: create issue card for this.

**Comment by lingtran** [comment]
To do:
- [ ] Test by rating forum messages and check if update totals are reflected on dashboard
- [ ] Create similar issue card for homepage

**Comment by lingtran** [comment]
Merged #26 with logic, but still need to confirm question about averageRating being null in data returned for getCourseRating request.

**Comment by lingtran** [comment]
Per conversation yesterday, pivoting Dashboard to encourage a different kind of behavior. Will create new card.
