### ISSUE TITLE
inbox new message button not working

### ISSUE THREAD

**Issue by nicolewang12** [Gabriel0402/COILFrontEnd#44]
When I click the new message button, I should be able to create a new message. Currently, when I click it, nothing happens.

**Comment by Gabriel0402** [comment]
what will the new message button  do? Should I remove it?

**Comment by nicolewang12** [comment]
The button is supposed to allowing people create new message, just like imessage on Iphone or messenger on Facebook would do. If time constricts, we can move it for this pilot, but I think eventually we should have this button.

**Comment by Gabriel0402** [comment]
Then I need mock up for the user list.

**Comment by nicolewang12** [comment]
I don't quite understand what is the user list?

**Comment by nicolewang12** [comment]
I see. I had it before, but I don't have it in the bootstrap version. Let's take out the button for now, and when I have time, I will give you the mock-up. Does that sound good?

**Comment by Gabriel0402** [comment]
Yes, Do you need me to remove the button?

**Comment by nicolewang12** [comment]
Sure, please go ahead and remove it. Thanks!
